services:
  development:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspace
      - ~/.gitconfig:/home/ubuntu/.gitconfig
      - ~/.ssh:/home/ubuntu/.ssh
    stdin_open: true